FROM --platform=$BUILDPLATFORM golang:1.22-alpine AS builder

WORKDIR /api

ENV CGO_ENABLED 0
ENV GOPATH /go
ENV GOCACHE /go-build

COPY go.mod go.sum ./
RUN --mount=type=cache,target=/go/pkg/mod/cache \
    go mod download

COPY . .

RUN --mount=type=cache,target=/go/pkg/mod/cache \
    --mount=type=cache,target=/go-build \
    go build -o bin/main cmd/main.go

CMD ["/bin/main"]







